repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-case-conflict

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: uv run mypy
        language: system
        types: [python]
        require_serial: true
        pass_filenames: true
    -   id: deptry
        name: deptry
        entry: uv run deptry .
        language: system
        types: [python]
        require_serial: true
        pass_filenames: false
